/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip,
    output reg red,
    output reg blue,
    output reg green,
    output reg hsync,
    output reg vsync
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [1-1:0] M_edge_detector_out;
  reg [1-1:0] M_edge_detector_in;
  edge_detector_2 edge_detector (
    .clk(clk),
    .in(M_edge_detector_in),
    .out(M_edge_detector_out)
  );
  wire [1-1:0] M_vga_red;
  wire [1-1:0] M_vga_blue;
  wire [1-1:0] M_vga_green;
  wire [1-1:0] M_vga_hsync;
  wire [1-1:0] M_vga_vsync;
  wire [4-1:0] M_vga_displayp11;
  wire [4-1:0] M_vga_displayp12;
  wire [4-1:0] M_vga_displayp21;
  wire [4-1:0] M_vga_displayp22;
  vga_3 vga (
    .clk(clk),
    .rst(rst),
    .up(io_button[2+0-:1]),
    .down(io_button[0+0-:1]),
    .up1(io_button[4+0-:1]),
    .down1(io_button[3+0-:1]),
    .red(M_vga_red),
    .blue(M_vga_blue),
    .green(M_vga_green),
    .hsync(M_vga_hsync),
    .vsync(M_vga_vsync),
    .displayp11(M_vga_displayp11),
    .displayp12(M_vga_displayp12),
    .displayp21(M_vga_displayp21),
    .displayp22(M_vga_displayp22)
  );
  wire [7-1:0] M_seg_seg;
  wire [4-1:0] M_seg_sel;
  reg [16-1:0] M_seg_values;
  multi_seven_seg_4 seg (
    .clk(clk),
    .rst(rst),
    .values(M_seg_values),
    .seg(M_seg_seg),
    .sel(M_seg_sel)
  );
  wire [16-1:0] M_dec_ctr_digits;
  reg [1-1:0] M_dec_ctr_inc;
  multi_dec_ctr_5 dec_ctr (
    .clk(clk),
    .rst(rst),
    .inc(M_dec_ctr_inc),
    .digits(M_dec_ctr_digits)
  );
  wire [1-1:0] M_ctr_value;
  counter_6 ctr (
    .clk(clk),
    .rst(rst),
    .value(M_ctr_value)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = {3'h0, io_button};
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    M_edge_detector_in = M_ctr_value;
    M_dec_ctr_inc = M_edge_detector_out;
    M_seg_values = {M_vga_displayp11, M_vga_displayp12, M_vga_displayp21, M_vga_displayp22};
    io_seg = ~M_seg_seg;
    io_sel = ~M_seg_sel;
    io_led = io_dip;
    red = M_vga_red;
    green = M_vga_green;
    blue = M_vga_blue;
    vsync = M_vga_vsync;
    hsync = M_vga_hsync;
  end
endmodule
