/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_13 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] sum1,
    output reg z,
    output reg v,
    output reg n,
    output reg overflow
  );
  
  
  
  reg [16:0] ssum;
  
  reg [16:0] sum;
  
  always @* begin
    
    case (alufn[0+1-:2])
      2'h0: begin
        ssum = a - b;
        sum = a + b;
      end
      2'h1: begin
        ssum = a - b;
        sum = a - b;
      end
      2'h2: begin
        ssum = a - b;
        sum = a * b;
      end
      2'h3: begin
        ssum = a - b;
        sum = a - (a / b * b);
      end
      default: begin
        ssum = a - b;
        sum = a + b;
      end
    endcase
    overflow = (a[15+0-:1] & b[15+0-:1] & (~sum[15+0-:1])) | ((~a[15+0-:1]) & (~b[15+0-:1]) & sum[15+0-:1]);
    sum1 = sum[0+15-:16];
    v = (a[15+0-:1] & ~b[15+0-:1] & (~ssum[15+0-:1])) | ((~a[15+0-:1]) & (b[15+0-:1]) & ssum[15+0-:1]);
    n = ssum[15+0-:1];
    z = (~|ssum);
  end
endmodule
